apiVersion: v1
kind: Service
metadata:
  namespace: UserService
  labels:
    app: UserService
  name: UserService
spec:
  ports:
  
    - protocol: TCP
      port: 4500
      targetPort: 4500
   
  selector:
    app: UserService
  type: ClusterIP
